Calendary/Calendary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include("home.urls")),
    path('accounts/', include("accounts.urls")),
    path('eventhub/', include("eventhub.urls")),

]

Calendary/eventhub/urls.py
from .views import CreateTagView, CreateTasksView, DeleteTagView, DeleteTasksView, ListTagsView, ListTasksView, ShareTaskView, TaskListView, UpdateTagView, UpdateTasksView, CalendarView, share_task_with_user
from django.urls import path

urlpatterns = [
    path("list_tasks/<int:year>/<int:month>/<int:day>/", ListTasksView.as_view(), name="list tasks"),
    path('tasks/', TaskListView.as_view(), name='task_list'),
    path('calendar/<int:year>/<int:month>/', CalendarView.as_view(), name='calendar'),
    path("create_task/", CreateTasksView.as_view(), name="create task"),
    path("update_task/<int:pk>/", UpdateTasksView.as_view(), name="update task"),
    path("delete_task/<int:pk>/", DeleteTasksView.as_view(), name="delete task"),

    path("list_tags/", ListTagsView.as_view(), name="list tags"),
    path("create_tag/", CreateTagView.as_view(), name="create tag"),
    path("update_tag/<int:pk>/", UpdateTagView.as_view(), name="update tag"),
    path("delete_tag/<int:pk>/", DeleteTagView.as_view(), name="delete tag"),

    path('task/<int:pk>/share/', ShareTaskView.as_view(), name='share_task'),
    path('task/<int:pk>/share-with-user/', share_task_with_user, name='share_task_with_user')
]

Calendary/home/urls.py
from django.urls import path
from .views import Home

urlpatterns = [
    path('', Home.as_view(), name="home")
]

Calendary/eventhub/models.py
from django.db import models
from accounts.models import User

class Tag(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20, default='#FFFFFF')
    users = models.ManyToManyField(User)

    def __str__(self) -> str:
        return self.name
    
class Task(models.Model):
    FREQUENCY_CHOICES = [
        ('daily', 'Diariamente'),
        ('weekly', 'Semanalmente'),
        ('monthly', 'Mensualmente'),
        ('yearly', 'Anualmente'),
    ]
    STATE_CHOICES = [
        ('pending', 'Pendiente'),
        ('in_progress', 'En progreso'),
        ('completed', 'Completada'),
        ('cancelled', 'Cancelada'),
    ]

    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    due_date = models.DateTimeField()
    state = models.CharField(max_length=20, choices=STATE_CHOICES, default='pending')
    tags = models.ManyToManyField(Tag, blank=True)
    users = models.ManyToManyField(User)
    creation_date = models.DateTimeField(auto_now_add=True)
    has_frequency = models.BooleanField(default=False)
    frequency = models.CharField(max_length=10, choices=FREQUENCY_CHOICES, blank=True, null=True, default=None)
    frequency_detail = models.CharField(max_length=100, blank=True, null=True, default=None)

    def __str__(self) -> str:
        return self.title

Calendary/eventhub/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout
from crispy_forms.bootstrap import FormActions
from .models import Task, Tag

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'due_date', 'tags', 'state']

        widgets = {
                'tags': forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(TaskForm, self).__init__(*args, **kwargs)
        
        # Filtrar las etiquetas que pertenecen al usuario
        if user:
            self.fields['tags'].queryset = Tag.objects.filter(users=user)
            

        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form_inputs" 
        
        # Establecer el atributo 'class' para el widget de fecha
        self.fields['due_date'].widget = forms.DateTimeInput(format='%Y-%m-%dT%H:%M', attrs={'type': 'datetime-local'})
        self.fields['due_date'].widget.attrs['class'] = 'datepicker'
        
        # Crear un objeto FormHelper
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            'title',
            'description',
            'due_date',
            'tags',
            'state',
            FormActions(
                Submit('submit', 'Guardar', css_class='btn btn-primary')
            )
        )
class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['name', 'color']

    def __init__(self, *args, **kwargs):
        super(TagForm, self).__init__(*args, **kwargs)
        self.fields['color'].widget.attrs['class'] = 'colorpicker'
        self.fields['color'].widget = forms.TextInput(attrs={'type':'color', 'id':'id_color'})

Calendary/eventhub/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.base import Model as Model
from django.http import Http404, JsonResponse
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, TemplateView, DetailView
from django.core.exceptions import PermissionDenied
from .models import Tag, Task
from .forms import TagForm, TaskForm
from calendar import SUNDAY, month, monthcalendar, setfirstweekday
from datetime import date, datetime, timedelta
from django.utils import timezone
from django.contrib import messages
from .utils import send_email
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

class CalendarView(LoginRequiredMixin, TemplateView):
    template_name = 'eventhub/calendar.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        year = int(self.kwargs.get('year', datetime.now().year))
        month = int(self.kwargs.get('month', datetime.now().month))

        setfirstweekday(SUNDAY)
        cal = monthcalendar(year, month)

        for week in cal:
            for i, day in enumerate(week):
                if day != 0:
                    week[i] = datetime(year, month, day)

        month_name = datetime(year, month, 1).strftime('%B')

        context['calendar'] = cal
        context['month_name'] = month_name
        context['year'] = year

        prev_month = month - 1
        prev_year = year
        if prev_month == 0:
            prev_month = 12
            prev_year -= 1

        # Calcular el mes siguiente
        next_month = month + 1
        next_year = year
        if next_month == 13:
            next_month = 1
            next_year += 1

        context['prev_month'] = prev_month
        context['prev_year'] = prev_year
        context['next_month'] = next_month
        context['next_year'] = next_year

        return context

class ListTasksView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "eventhub/list.html"

    def get_queryset(self):

        # Validar que se proporcionó el parámetro day en la URL
        year = int(self.kwargs.get('year', datetime.now().year))
        month = int(self.kwargs.get('month', datetime.now().month))
        day = int(self.kwargs.get('day', datetime.now().day))

        # Validar que se proporcionó el parámetro day en la URL
        if not (day and month and year):
            raise Http404("Los parámetros 'day', 'month' y 'year' son obligatorios en la URL.")

        # Convertir los valores de year, month y day a un objeto datetime
        start_date = timezone.make_aware(timezone.datetime(year, month, day))
        end_date = start_date + timezone.timedelta(days=1)

        # Filtrar las tareas por usuario, año, mes y día
        return Task.objects.filter(users=self.request.user, due_date__range=(start_date, end_date))    

class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = 'task_list.html'
    context_object_name = 'tasks'
    paginate_by = 5

    def get_queryset(self):
        queryset = super().get_queryset().filter(users=self.request.user)
        state = self.request.GET.getlist('state')
        tags = self.request.GET.getlist('tags')
        date_range = self.request.GET.get('date_range')
        date_interval = self.request.GET.get('date_interval')
        if state:
            queryset = queryset.filter(state__in = state)
        if tags:
            queryset = queryset.filter(tags__name__in=tags)
        if date_range:
            today = timezone.now().date()

            if date_range == 'today':
                end_date = timezone.make_aware(timezone.datetime.combine(today, timezone.datetime.min.time())) + timezone.timedelta(days=1)
                queryset = queryset.filter(due_date__range=[today, end_date])
            elif date_range == 'this_week':
                start_week = timezone.make_aware(timezone.datetime.combine(today - timedelta(days=today.weekday()), timezone.datetime.min.time()))
                end_week = start_week + timedelta(days=6)
                queryset = queryset.filter(due_date__range=[start_week, end_week])
            elif date_range == 'this_month':
                first_day_of_month = timezone.make_aware(timezone.datetime.combine(today.replace(day=1), timezone.datetime.min.time()))
                # Obtener el último día del mes actual
                last_day_of_month = (first_day_of_month + timedelta(days=32)).replace(day=1) - timedelta(days=1)
                
                queryset = queryset.filter(due_date__range=[first_day_of_month, last_day_of_month])

        if date_interval:
            today = timezone.now().date()
            end_date = (timezone.make_aware(datetime.strptime(date_interval, '%Y-%m-%d')) + timedelta(days=1)).date()
            if end_date < today:
                print("La fecha final es anterior a la fecha actual. No se puede filtrar en el pasado.")
            else:
                print(f"today: {today}, end_date: {end_date}")
                queryset = queryset.filter(due_date__range=[today, end_date])

        return queryset.order_by('due_date')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['states'] = Task.STATE_CHOICES
        context['tags'] = Tag.objects.filter(users=self.request.user)
        return context
        
class CreateTasksView(LoginRequiredMixin, CreateView):
    template_name = "eventhub/form.html"
    form_class = TaskForm
    model = Task
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Crear Tarea"
        context['form_action'] = reverse('create task')
        context['id'] = "createTaskForm"
        return context
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        response = super().form_valid(form)
        self.object.users.add(self.request.user)
        send_email(self.object, self.request.user)
        response_data = {'message': 'Tarea creada exitosamente'}
        return JsonResponse(response_data)


    def form_invalid(self, form):
        response_data = {'message': 'Hubo un error al crear la tarea'}
        return JsonResponse(response_data, status=400)
    
    def get_success_url(self):
        messages.success(self.request, 'Tarea creada exitosamente')
        return reverse_lazy('list tasks', kwargs={'year': self.object.due_date.year, 'month': self.object.due_date.month, 'day': self.object.due_date.day})

class UpdateTasksView(LoginRequiredMixin, UpdateView):
    template_name =  "eventhub/form.html"
    form_class = TaskForm
    model = Task
    
    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        # Verificar si el usuario tiene acceso al objeto
        if obj.users.filter(pk=self.request.user.pk).exists():
            return obj
        else:
            raise PermissionDenied("No tienes permisos para acceder a esta tarea.")
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        self.object = form.save()
        response_data = {'message': 'Tarea Actualizada exitosamente'}
        return JsonResponse(response_data)

    def form_invalid(self, form):
        response_data = {'message': 'Hubo un error al actualizar la tarea'}
        return JsonResponse(response_data, status=400)
    
    def get_success_url(self):
        messages.success(self.request, 'Tarea actualizada exitosamente')
        return reverse_lazy('list tasks', kwargs={'year': self.object.due_date.year, 'month': self.object.due_date.month, 'day': self.object.due_date.day})
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task_id = self.kwargs.get('pk')
        context['title'] = "Actualizar Tarea"
        context['form_action'] = reverse('update task', kwargs={'pk': task_id})
        context['id'] = 'updateTaskForm'
        return context
    
class DeleteTasksView(LoginRequiredMixin, DeleteView):
    template_name = "eventhub/form.html"
    model = Task

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        # Verificar si el usuario tiene acceso al objeto
        if obj.users.filter(pk=self.request.user.pk).exists():
            return obj
        else:
            raise PermissionDenied("No tienes permisos para acceder a esta tarea.")
        
    def form_valid(self, form):
        self.get_object().delete()
        response_data = {'message': 'Tarea eliminada exitosamente'}
        return JsonResponse(response_data)
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task_id = self.kwargs.get('pk')
        context['title'] = "Eliminar Tarea"
        context['form_action'] = reverse('delete task', kwargs={'pk': task_id})
        context['id'] = 'deleteTaskForm'
        return context
    
    def get_success_url(self):
        messages.success(self.request, 'Tarea eliminada exitosamente')
        return reverse_lazy('list tasks', kwargs={'year': self.object.due_date.year, 'month': self.object.due_date.month, 'day': self.object.due_date.day})

class ListTagsView(LoginRequiredMixin, ListView):
    model = Tag
    template_name = "eventhub/tags.html"

    def get_queryset(self):
        return Tag.objects.filter(users=self.request.user)
        
class CreateTagView(LoginRequiredMixin, CreateView):
    template_name = "eventhub/form.html"
    form_class = TagForm
    model = Tag

    def get_context_data(self, **kwargs):

Calendary/eventhub/templates/eventhub/calendar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static "eventhub/css/style.css" %}">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <script src="{% static "eventhub/js/modal.js" %}"></script>
    <script src="{% static "eventhub/js/task_list.js" %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <title>Calendario</title>
  </head>
  <body>
    <div class="header">
      <a class="nav-calendar" href="{% url 'calendar' year=prev_year month=prev_month %}"><i class='bx bx-chevron-left'></i></a>
      <button class="ButCalendario" id="calendar-view"><h2>{{ month_name }} {{ year }} Calendar</h2></button>
      <a class="nav-calendar" href="{% url 'calendar' year=next_year month=next_month %}"><i class='bx bx-chevron-right' ></i></a>
    </div>
    <div class="todo">
      <div class="Botareas">
        <button id="createTaskBtn">Create Task</button>
        <button id="listTagsBtn">Tags</button>
        <button id="taskslistBtn">Tasks</button>
      </div>
      
      <div class="calendar-container">
      <ul class="calendar">
        <li class="day-header sun">Sun</li>
        <li class="day-header mon">Mon</li>
        <li class="day-header tue">Tue</li>
        <li class="day-header wed">Wed</li>
        <li class="day-header thu">Thu</li>
        <li class="day-header fri">Fri</li>
        <li class="day-header sat">Sat</li>
        {% for week in calendar %} {% for day in week %} {% if day == 0 %}
        <li class="empty-day"></li>
        {% else %}
        <li class="day">
          <button class="date listTasksBtn" data-year="{{ day.year }}" data-month="{{ day.month}}" data-day="{{ day.day }}">{{ day.day }}</button>
        </li>
        {% endif %} {% endfor %} {% endfor %}
      </ul>
    </div>
    </div>
    
    
    <!-- The Modal -->
    <div id="myModal" class="modal">
      <!-- Modal content -->
      <div class="modal-content">
        <span class="close">&times;</span>
        <p>Hubo un error al cargar el modal</p>
      </div>
    </div>
  </body>
</html>

Calendary/eventhub/templates/eventhub/form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <link rel="stylesheet" href="{% static "eventhub/css/formStyle.css" %}">
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="{% static "eventhub/js/form.js" %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <title>Document</title>
  </head>
  <body>
    <div class="modal-title-bar">
      <h2>{{ title }}</h2>
      <span class="close">&times;</span>
    </div>
    <form method="POST" action="{{ form_action }}" id="{{ id }}">
      {% csrf_token %} {{ form.as_p }}
      <button type="submit" onclick="submitFormAndCloseModal('{{ id }}', event)" id="submit-button">Create</button>
    </form>
  </body>
</html>

Calendary/eventhub/templates/eventhub/list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="{% static "eventhub/js/list.js" %}"></script>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <title>Document</title>
  </head>
  <body>
    <div class="modal-title-bar">
      <h2>Lista de tareas</h2>
      <span class="close">&times;</span>
    </div>
    {% if object_list %}
    <ul>
      {% for task in object_list %}
      {% if task.tags.all %}
      <li class="tasks" style="border-left: 10px solid {{ task.tags.first.color }};">
          <div class="task-info">
              <strong>{{ task.title }}</strong><br />
              Descripción: {{ task.description }}<br />
              Fecha de vencimiento: {{ task.due_date }}<br />
              Tags:
              {% for tag in task.tags.all %}
                  {{ tag.name }}
                  {% if not forloop.last %},{% endif %}
              {% endfor %}
          </div>
          <div class="task-options">
              <button class="shareTaskBtn"  data-task-id='{{ task.id }}'><i class='bx bxs-share'></i></button>
              <button class='updateTaskBtn' data-task-id='{{ task.id }}'><i class='bx bxs-pencil'></i></button>
              <button class='deleteTaskBtn' data-task-id='{{ task.id }}'><i class='bx bxs-trash-alt'></i></button>
          </div>
      </li>
      {% else %}
      <li class="tasks">
          <div class="task-info">
              <strong>{{ task.title }}</strong><br />
              Descripción: {{ task.description }}<br />
              Fecha de vencimiento: {{ task.due_date }}
          </div>
          <div class="task-options">
              <button class="shareTaskBtn"  data-task-id='{{ task.id }}'><i class='bx bxs-share'></i></button>
              <button class='updateTaskBtn' data-task-id='{{ task.id }}'><i class='bx bxs-pencil'></i></button>
              <button class='deleteTaskBtn' data-task-id='{{ task.id }}'><i class='bx bxs-trash-alt'></i></button>
          </div>
      </li>
      {% endif %}
      {% endfor %}
    </ul>
    {% else %}
    <p>No hay tareas para hoy</p>
    {% endif %}
  </body>
</html>

Calendary/eventhub/templates/eventhub/share_task.html
<!DOCTYPE html>
<html>
  <head>
    {% load static %}
    <title>Compartir tarea</title>
    <link rel="stylesheet" href="{% static "eventhub/css/style.css" %}">
    <script src="{% static "eventhub/js/share_task.js" %}"></script>
  </head>
  <body>
    <div class="modal-title-bar">
        <h2>Compartir tarea: {{ task.title }}</h2>
        <span class="close">&times;</span>
      </div>
    <p>{{ task.description }}</p>
    <p>Fecha de vencimiento: {{ task.due_date }}</p>
    <p>Estado: {{ task.get_state_display }}</p>
    <p>Etiquetas: {{ task.tags.all|join:", " }}</p>

    <h3>Usuarios compartidos:</h3>
    <ul>
      {% for user in task.users.all %}
      <li>{{ user.username }}</li>
      {% endfor %}
    </ul>

    <button class="shareTaskWithUserBtn" data-task-id="{{ task.id }}" data-link="{% url 'share_task_with_user' pk=task.pk %}">Compartir con otro usuario</button>
  </body>
</html>

Calendary/eventhub/templates/eventhub/tags.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="{% static "eventhub/js/tags.js" %}"></script>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <title>Document</title>
  </head>
  <body>
    <div class="modal-title-bar">
      <h2>Lista de Etiquetas</h2>
        <div class="actions">
            <span id="createTagBtn" class="create">+</span>
            <span class="close">&times;</span>
        </div>
    </div>
    {% if object_list %}
    <ul>
      {% for tag in object_list %}
      <li class="tasks">
        <div class="tag-info">
          <strong>{{ tag.name }}</strong><br />
        Color: {{ tag.color }}<br />
        <div style="width: 20px; height: 20px; background-color: {{tag.color}}; border: 1px solid #000;"></div>
        </div>
        <div class="task-options">
            <button class='updateTagBtn' data-tag-id='{{ tag.id }}'><i class='bx bxs-pencil'></i></button>
            <button class='deleteTagBtn' data-tag-id='{{ tag.id }}'><i class='bx bxs-trash-alt'></i></button>
        </div>
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <p>No hay etiquetas</p>
    {% endif %}
  </body>
</html>

Calendary/eventhub/templates/eventhub/task_list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <script src="{% static "eventhub/js/list.js" %}"></script>
    <title>Document</title>
  </head>
  <body>
    <div class="modal-title-bar">
      <h2>Lista de Tareas</h2>
      <div class="actions">
        <span class="close">&times;</span>
      </div>
    </div>
    <div class="infor">
      <form method="get">
        <div class="opState">
          <label>State:</label>
          <div class="cuadrosState">
            {% for state in states %}
            <div class="checkbox-option">
              <input
                type="checkbox"
                id="state_{{ state.0 }}"
                name="state"
                value="{{ state.0 }}"
              />
              <label for="state_{{ state.0 }}">{{ state.1 }}</label>
            </div>
            {% endfor %}
          </div>
        </div>
        <div class="opTags">
          <label>Tags:</label>
          <div class="cuadrosTags">
            {% for tag in tags %}
            <div class="checkbox-option">
              <input
                type="checkbox"
                id="tag_{{ tag.id }}"
                name="tags"
                value="{{ tag.name }}"
              />
              <label for="tag_{{ tag.id }}">{{ tag.name }}</label>
            </div>
            {% endfor %}
          </div>
        </div>
        <div class="fecha">
          <label for="date_range">Date Range:</label>
          <select id="date_range" name="date_range">
            <option value="">All</option>
            <option value="today">Today</option>
            <option value="this_week">This Week</option>
            <option value="this_month">This Month</option>
          </select>
        </div>
        <div class="intervalo">
          <label for="date_interval">Date Interval:</label>
          <input type="date" id="date_interval" name="date_interval" />
        </div>
        <button id="apply-filters-btn" type="submit">Filter</button>
      </form>
      {% if object_list %}
      <ul class="task-container">
        {% for task in object_list %} {% if task.tags.all %}
        <li
          class="tasks"
          style="border-left: 10px solid {{ task.tags.first.color }};"
        >
          <div class="task-info">
            <strong>{{ task.title }}</strong><br />
            Descripción: {{ task.description }}<br />
            Fecha de vencimiento: {{ task.due_date }}<br />
            Tags:{% for tag in task.tags.all %}
            {{ tag.name }}
            {% if not forloop.last %},{% endif %}
            {% endfor %}
          </div>
          <div class="task-options">
            <button class="shareTaskBtn" data-task-id="{{ task.id }}">
              <i class="bx bxs-share"></i>
            </button>
            <button class="updateTaskBtn" data-task-id="{{ task.id }}">
              <i class="bx bxs-pencil"></i>
            </button>
            <button class="deleteTaskBtn" data-task-id="{{ task.id }}">
              <i class="bx bxs-trash-alt"></i>
            </button>
          </div>
        </li>
        {% else %}
        <li class="tasks">
          <div class="task-info">
            <strong>{{ task.title }}</strong><br />
            Descripción: {{ task.description }}<br />
            Fecha de vencimiento: {{ task.due_date }}
          </div>
          <div class="task-options">
            <button class="shareTaskBtn" data-task-id="{{ task.id }}">
              <i class="bx bxs-share"></i>
            </button>
            <button class="updateTaskBtn" data-task-id="{{ task.id }}">
              <i class="bx bxs-pencil"></i>
            </button>
            <button class="deleteTaskBtn" data-task-id="{{ task.id }}">
              <i class="bx bxs-trash-alt"></i>
            </button>
          </div>
        </li>
        {% endif %} {% endfor %}
        <div class="pagination">
          <span class="step-links">
              {% if page_obj.has_previous %}
                  <a class="pagination-link" href="{% url 'task_list' %}?page=1{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">&laquo; first</a>
                  <a class="pagination-link" href="{% url 'task_list' %}?page={{ page_obj.previous_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">previous</a>
              {% endif %}
      
              <span class="current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
      
              {% if page_obj.has_next %}
                  <a class="pagination-link" href="{% url 'task_list' %}?page={{ page_obj.next_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">next</a>
                  <a class="pagination-link" href="{% url 'task_list' %}?page={{ page_obj.paginator.num_pages }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">last &raquo;</a>
              {% endif %}
          </span>
      </div>
      </ul>
      {% else %}
      <p>No hay tareas para hoy</p>
      {% endif %}
    </div>
  </body>
</html>